# Generated by Django 3.2.13 on 2022-09-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220831_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ssafyclass',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
